/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.table.DefaultTableModel;
import java.awt.Image;
import static java.lang.String.format;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.databaseConnection;
/**
 *
 * @author babsybabu
 */
public class adoptedPetsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form petShelterJPanel
     */
    databaseConnection databaseConnection;

    public adoptedPetsJPanel(databaseConnection databaseConnection) {
        initComponents();
        this.databaseConnection=databaseConnection;
        populateTable();
    }
    
        private void populateTable() {
         try {
            ResultSet result = databaseConnection.executeSelect("SELECT * FROM adoptedPets");
            DefaultTableModel model = (DefaultTableModel) tblPetAdoptionRecords.getModel();
            model.setRowCount(0);
            while(result.next())
            {
                
            Object[]row=new Object[10];
                row[0] = result.getInt("id");
                row[1] = result.getString("user_id");
                row[2] = result.getString("pet_id");
                row[3] = result.getString("pet_name");
            
            model.addRow(row);
                    
            
        }
        } catch (Exception ex) {
            Logger.getLogger(kennelAdminUpdatePrice.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPetAdoptionRecords = new javax.swing.JTable();
        lblImg = new javax.swing.JLabel();

        tblPetAdoptionRecords.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "User ID", "Pet ID", "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPetAdoptionRecords.setBounds(new java.awt.Rectangle(0, 0, 568, 191));
        jScrollPane1.setViewportView(tblPetAdoptionRecords);
        if (tblPetAdoptionRecords.getColumnModel().getColumnCount() > 0) {
            tblPetAdoptionRecords.getColumnModel().getColumn(1).setResizable(false);
            tblPetAdoptionRecords.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1088, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblImg;
    private javax.swing.JTable tblPetAdoptionRecords;
    // End of variables declaration//GEN-END:variables
}
