/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author babsybabu
 */
public class petShelterAdmin extends javax.swing.JPanel {

    /**
     * Creates new form petShelterAdmin
     */
    public petShelterAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        shelterAdminSplitPane = new javax.swing.JSplitPane();
        shelterAdminControlArea = new javax.swing.JPanel();
        shelterAdminWorkArea = new javax.swing.JPanel();

        javax.swing.GroupLayout shelterAdminControlAreaLayout = new javax.swing.GroupLayout(shelterAdminControlArea);
        shelterAdminControlArea.setLayout(shelterAdminControlAreaLayout);
        shelterAdminControlAreaLayout.setHorizontalGroup(
            shelterAdminControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        shelterAdminControlAreaLayout.setVerticalGroup(
            shelterAdminControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 419, Short.MAX_VALUE)
        );

        shelterAdminSplitPane.setLeftComponent(shelterAdminControlArea);

        javax.swing.GroupLayout shelterAdminWorkAreaLayout = new javax.swing.GroupLayout(shelterAdminWorkArea);
        shelterAdminWorkArea.setLayout(shelterAdminWorkAreaLayout);
        shelterAdminWorkAreaLayout.setHorizontalGroup(
            shelterAdminWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 853, Short.MAX_VALUE)
        );
        shelterAdminWorkAreaLayout.setVerticalGroup(
            shelterAdminWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 419, Short.MAX_VALUE)
        );

        shelterAdminSplitPane.setRightComponent(shelterAdminWorkArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(shelterAdminSplitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(shelterAdminSplitPane)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel shelterAdminControlArea;
    private javax.swing.JSplitPane shelterAdminSplitPane;
    private javax.swing.JPanel shelterAdminWorkArea;
    // End of variables declaration//GEN-END:variables
}
