/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.table.DefaultTableModel;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.petProfileForAdoption;
import model.petAdoptionRecords;
/**
 *
 * @author babsybabu
 */
public class petShelterJPanel extends javax.swing.JPanel {

    /**
     * Creates new form petShelterJPanel
     */
    petAdoptionRecords records;
    public petShelterJPanel(petAdoptionRecords records) {
        initComponents();
        this.records=records;
        System.out.println(records.getRecords());

        populateTable();
    }
    
        private void populateTable() {
        DefaultTableModel model=(DefaultTableModel) tblPetAdoptionRecords.getModel();
        model.setRowCount(0);
        
        for(petProfileForAdoption pet:records.getRecords()){
            System.out.println(pet);
            Object[]row=new Object[10];
            row[0]=pet;
            row[1]=pet.getName();
            row[2]=pet.getPetId();
            row[3]=pet.getBreed();
            row[4]=pet.getGender();
            row[5]=pet.getDob();
            row[6]=pet.getAge();
            row[7]=pet.getHeight();
            row[8]=pet.getWeight();
            row[9]=pet.getVaccinationStatus();
            
            model.addRow(row);
                    
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPetAdoptionRecords = new javax.swing.JTable();
        btnAdopt = new javax.swing.JButton();
        lblImg = new javax.swing.JLabel();
        btnViewImage = new javax.swing.JButton();

        tblPetAdoptionRecords.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "ID", "Breed", "Gender", "Date of Birth", "Age", "Height", "Weight", "Vaccination Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPetAdoptionRecords.setBounds(new java.awt.Rectangle(0, 0, 568, 191));
        jScrollPane1.setViewportView(tblPetAdoptionRecords);

        btnAdopt.setText("Adopt");
        btnAdopt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdoptActionPerformed(evt);
            }
        });

        btnViewImage.setText("View Image");
        btnViewImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewImageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1088, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnAdopt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewImage)
                .addGap(432, 432, 432)
                .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdopt)
                            .addComponent(btnViewImage))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewImageActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex=tblPetAdoptionRecords.getSelectedRow();
        System.out.println(selectedRowIndex);
        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this,"Please select a row to view");
            return;
        }
        
        DefaultTableModel model=(DefaultTableModel) tblPetAdoptionRecords.getModel();
        petProfileForAdoption emp=(petProfileForAdoption)model.getValueAt(selectedRowIndex, 0);
        
        if(emp.getImgPath()==null){
            lblImg.setIcon(new ImageIcon("/Users/babsybabu/Downloads/no-photo-uploaded.gif"));
        }
        else{
            Image finalImage=emp.getImage().getScaledInstance(300,300,Image.SCALE_DEFAULT);
            lblImg.setIcon(new ImageIcon(finalImage));
        }
    }//GEN-LAST:event_btnViewImageActionPerformed

    private void btnAdoptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdoptActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnAdoptActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdopt;
    private javax.swing.JButton btnViewImage;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblImg;
    private javax.swing.JTable tblPetAdoptionRecords;
    // End of variables declaration//GEN-END:variables
}
