/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.util.logging.Level;
import java.util.logging.Logger;
import model.databaseConnection;
import model.sendEmail;
import model.sendSMS;

/**
 *
 * @author shrey
 */
public class userJPanel extends javax.swing.JPanel {

    /**
     * Creates new form userJPanel
     */
    int userID;
    sendEmail emailNotification;
    sendSMS smsNotification;
    databaseConnection databaseConnection;
    
    public userJPanel(databaseConnection databaseConnection, int userID, sendEmail emailNotification, sendSMS smsNotification) {
        initComponents();
        this.userID = userID;
        this.emailNotification = emailNotification;
        this.smsNotification = smsNotification;
        this.databaseConnection = databaseConnection;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        foodAccsJPanel = new javax.swing.JPanel();
        foodAccsSplitPane = new javax.swing.JSplitPane();
        foodAccsControlArea = new javax.swing.JPanel();
        btnPetFood = new javax.swing.JButton();
        btnPetGrooming = new javax.swing.JButton();
        btnPetAccessories = new javax.swing.JButton();
        foodAccsWorkArea = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 102));

        tabbedPane.setBackground(new java.awt.Color(255, 255, 102));
        tabbedPane.setForeground(new java.awt.Color(0, 0, 255));
        tabbedPane.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        foodAccsSplitPane.setDividerLocation(135);

        foodAccsControlArea.setBackground(new java.awt.Color(102, 255, 102));

        btnPetFood.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnPetFood.setForeground(new java.awt.Color(255, 0, 0));
        btnPetFood.setText("Pet Food");
        btnPetFood.setPreferredSize(new java.awt.Dimension(76, 35));
        btnPetFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPetFoodActionPerformed(evt);
            }
        });

        btnPetGrooming.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnPetGrooming.setForeground(new java.awt.Color(255, 0, 0));
        btnPetGrooming.setText("Pet Grooming");
        btnPetGrooming.setPreferredSize(new java.awt.Dimension(76, 35));
        btnPetGrooming.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPetGroomingActionPerformed(evt);
            }
        });

        btnPetAccessories.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnPetAccessories.setForeground(new java.awt.Color(255, 0, 0));
        btnPetAccessories.setText("Pet Accessories");
        btnPetAccessories.setPreferredSize(new java.awt.Dimension(76, 35));
        btnPetAccessories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPetAccessoriesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout foodAccsControlAreaLayout = new javax.swing.GroupLayout(foodAccsControlArea);
        foodAccsControlArea.setLayout(foodAccsControlAreaLayout);
        foodAccsControlAreaLayout.setHorizontalGroup(
            foodAccsControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(foodAccsControlAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(foodAccsControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPetFood, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(btnPetGrooming, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(btnPetAccessories, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        foodAccsControlAreaLayout.setVerticalGroup(
            foodAccsControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(foodAccsControlAreaLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(btnPetFood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(btnPetAccessories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(btnPetGrooming, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(214, Short.MAX_VALUE))
        );

        foodAccsSplitPane.setLeftComponent(foodAccsControlArea);

        foodAccsWorkArea.setBackground(new java.awt.Color(0, 255, 255));

        javax.swing.GroupLayout foodAccsWorkAreaLayout = new javax.swing.GroupLayout(foodAccsWorkArea);
        foodAccsWorkArea.setLayout(foodAccsWorkAreaLayout);
        foodAccsWorkAreaLayout.setHorizontalGroup(
            foodAccsWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
        );
        foodAccsWorkAreaLayout.setVerticalGroup(
            foodAccsWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 569, Short.MAX_VALUE)
        );

        foodAccsSplitPane.setRightComponent(foodAccsWorkArea);

        javax.swing.GroupLayout foodAccsJPanelLayout = new javax.swing.GroupLayout(foodAccsJPanel);
        foodAccsJPanel.setLayout(foodAccsJPanelLayout);
        foodAccsJPanelLayout.setHorizontalGroup(
            foodAccsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(foodAccsSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
        );
        foodAccsJPanelLayout.setVerticalGroup(
            foodAccsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(foodAccsSplitPane)
        );

        tabbedPane.addTab("Food & Accessories", foodAccsJPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 25, Short.MAX_VALUE)
                .addComponent(tabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPetFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPetFoodActionPerformed
        try {
            // TODO add your handling code here:
            petFoodJPanel petfoodPanel = new petFoodJPanel(databaseConnection, userID, emailNotification, smsNotification);
            foodAccsSplitPane.setRightComponent(petfoodPanel);
        } catch (Exception ex) {
            Logger.getLogger(userJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPetFoodActionPerformed

    private void btnPetGroomingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPetGroomingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPetGroomingActionPerformed

    private void btnPetAccessoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPetAccessoriesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPetAccessoriesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPetAccessories;
    private javax.swing.JButton btnPetFood;
    private javax.swing.JButton btnPetGrooming;
    private javax.swing.JPanel foodAccsControlArea;
    private javax.swing.JPanel foodAccsJPanel;
    private javax.swing.JSplitPane foodAccsSplitPane;
    private javax.swing.JPanel foodAccsWorkArea;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
}
